version: '2.3'

services:
  pd0:
    image: pingcap/pd:latest
    ports:
      - "2379:2379"
    volumes:
      - ./config/pd.toml:/pd.toml:ro
      - ./data:/data
    command:
      - --name=pd0
      - --client-urls=http://0.0.0.0:2379
      - --peer-urls=http://0.0.0.0:2380
      - --advertise-client-urls=http://pd0:2379
      - --advertise-peer-urls=http://pd0:2380
      - --initial-cluster=pd0=http://pd0:2380
      - --data-dir=/data/pd0
      - --config=/pd.toml
    restart: on-failure
  tikv0:
    image: pingcap/tikv:latest
    ports:
      - "20160:20160"
    volumes:
      - ./config/tikv.toml:/tikv.toml:ro
      - ./data:/data
    command:
      - --addr=0.0.0.0:20160
      - --advertise-addr=tikv0:20160
      - --data-dir=/data/tikv0
      - --pd=pd0:2379
      - --config=/tikv.toml
    depends_on:
      - "pd0"
    restart: on-failure
  tidb:
    image: pingcap/tidb:latest
    ports:
      - "4000:4000"
      - "10080:10080"
    volumes:
      - ./config/tidb.toml:/tidb.toml:ro
    command:
      - --store=tikv
      - --path=pd0:2379
      - --config=/tidb.toml
      - -L=warn
    depends_on:
      - "tikv0"
    restart: on-failure
  tispark-master:
    #build: ./tispark
    image: mars/tispark:latest
    command:
      - /opt/spark/sbin/start-master.sh
    volumes:
      - ./config/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf:ro
      - ./jars/tispark-core-2.1-SNAPSHOT-jar-with-dependencies.jar:/opt/spark/jars/tispark-core-2.1-SNAPSHOT-jar-with-dependencies.jar:ro
    environment:
      SPARK_MASTER_PORT: 7077
      SPARK_MASTER_WEBUI_PORT: 8080
    ports:
      - "7077:7077"
      - "8080:8080"
    depends_on:
      - "tikv0"
    restart: on-failure
  tispark-slave0:
    #build: ./tispark
    image: mars/tispark:latest
    command:
      - /opt/spark/sbin/start-slave.sh
      - spark://tispark-master:7077
    volumes:
      - ./config/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf:ro
      - ./jars/tispark-core-2.1-SNAPSHOT-jar-with-dependencies.jar:/opt/spark/jars/tispark-core-2.1-SNAPSHOT-jar-with-dependencies.jar:ro
    environment:
      SPARK_WORKER_WEBUI_PORT: 38081
    ports:
      - "38081:38081"
    depends_on:
      - tispark-master
    restart: on-failure
  zeppelin:
    image: mars/zeppelin:latest
    ports:
      - "80:8080"
    volumes:
      - ./notebook:/opt/zeppelin/notebook
      - ./config/spark-defaults.conf:/opt/spark/conf/spark-defaults.conf:ro
      - ./jars/tispark-core-2.1-SNAPSHOT-jar-with-dependencies.jar:/opt/spark/jars/tispark-core-2.1-SNAPSHOT-jar-with-dependencies.jar:ro
    environment:
      SPARK_MASTER: "spark://tispark-master:7077"
      MASTER: "spark://tispark-master:7077"
    depends_on:
      - tispark-master
